__all__ = [
    "FORMAT_BED4",
    "FORMAT_TRF",
    "FORMAT_TRGT",
    "CONVERTER_IN_FORMATS",
]

FORMAT_BED4 = "bed4"
FORMAT_TRF = "trf"
FORMAT_TRGT = "trgt"

CONVERTER_IN_FORMATS = (
    FORMAT_BED4,
    FORMAT_TRF,
    FORMAT_TRGT,
)
