name: Publish PyPI release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    environment:
      name: release
      url: https://pypi.org/p/strkit

    env:
      UV_NO_SOURCES: '1'  # force using PyPI version of strkit_rust_ext

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        name: Set up Python
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build
        run: uv build

      - name: Publish
        uses: uv publish
